### ISSUE TITLE
👽 [FIX] 채팅 내역, 상세 페이지 프롬프트 api 변경

### ISSUE THREAD

**Issue by adorableco** [A-hi-11/A-hi-frontend#44]
### To-do
- [ ] 프롬프트 내에서는 `/api/use/` 로 통일
- [ ] 채팅 내역 내에서는 `/api/` 로 통일
- [ ] 프롬프트 상세 페이지에서 이전 대화내역 끌어오기 (`chat_room_id` 받아야함)
